import Head from "next/head";
import styles from "../styles/Home.module.css";
import CustomMasonry from "../components/CustomMasonry/CustomMasonry";

export default function Home() {
  return (
    <>
      <Head>
        <title>Siłownia Krzepa | Sala cardio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CustomMasonry />
      </main>
    </>
  );
}
