import Head from "next/head";
import styles from "../styles/Home.module.css";
import CustomCarousel from "../components/CustomCarousel/CustomCarousel";

export default function Home() {
  return (
    <>
      <Head>
        <title>Siłownia Krzepa | Galeria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CustomCarousel />
      </main>
    </>
  );
}
