import Head from "next/head";
import styles from "../styles/Home.module.css";
import CustomRules from "../components/CustomRules/CustomRules";

export default function Home() {
  return (
    <>
      <Head>
        <title>Siłownia Krzepa | Regulamin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CustomRules />
      </main>
    </>
  );
}
